rabbitmq:
  user-exchange-name: 'user'
  url: 'amqp://admin:admin@localhost:5672/'
user-service:
  project-name: 'user-service'
  ip: 'localhost'
  port: 5001
frontend-gateway:
  project-name: 'frontend-gateway'
  ip: 'localhost'
  port: 5000
