db:
  ip: "localhost"
  password: "password"
  username: "root"
  port: 27017
  name: 'users'
auth:
  pepper-letters: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
  pepper-length: 4
rabbitmq:
  user-exchange-name: 'user'
  url: 'amqp://admin:admin@localhost:5672/'