apiVersion: v1
data:
  FRONTEND_GATEWAY_IP: ICdmcm9udGVuZC1nYXRld2F5Jw==
  FRONTEND_GATEWAY_PORT: IDUwMDA=
  FRONTEND_GATEWAY_PROJECT_NAME: ICdmcm9udGVuZC1nYXRld2F5Jw==
kind: Secret
metadata:
  creationTimestamp: "2024-12-12T13:04:12Z"
  name: person
  namespace: default
  resourceVersion: "3748"
  uid: 7543c68c-3b8b-47ff-9471-55ff3415e2f6
type: Opaque
