version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    hostname: 'rabbitmq'
    restart: unless-stopped
    volumes:
      - '../volumes/rabbitmq/rabbitmq_data/:/var/lib/rabbitmq'
      - '../volumes/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config'
      - '../volumes/rabbitmq/logs:/var/log'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - common-network
