services:
  user-service:
    container_name: user-service
    restart: unless-stopped
    build:
      context: '../../apps/user'
      dockerfile: 'Dockerfile'
    depends_on:
      - mongodb
    networks:
      - common-network
