services:
  user-service:
    container_name: user-service
    restart: unless-stopped
    build:
      context: '../..'
      dockerfile: '/apps/user/Dockerfile'
    depends_on:
      - mongodb
    networks:
      - common-network
