services:
  frontend-gateway:
    container_name: frontend-gateway
    restart: unless-stopped
    build:
      context: '../../../'
      dockerfile: 'apps/frontend_gateway/Dockerfile'
    env_file:
      - deployment/configs/project_base_info/frontend-gateway.env
      - deployment/configs/project_base_info/user-service.env
      - deployment/configs/project_personal_info/frontend-gateway.env


    networks:
      - common-network
