services:
  frontend-gateway:
    container_name: frontend-gateway
    restart: unless-stopped
    build:
      context: '../../../'
      dockerfile: 'apps/frontend_gateway/Dockerfile'
    env_file:
      - ../../configs/frontend-gateway.env
      - ../../configs/network.env
    networks:
      - common-network
