services:
  mongodb:
    image: mongo
    container_name: mongodb-service
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - '../volumes/mongodb/data:/data/db'
    env_file:
      - ../../configs/mongodb.env
    networks:
      - common-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - ../../configs/mongo-express.env
    depends_on:
      - mongodb
    networks:
      - common-network

