services:
  user-service:
    container_name: user-service
    restart: unless-stopped
    build:
      context: '../../../'
      dockerfile: 'apps/user/Dockerfile'
    depends_on:
      - mongodb
    env_file:
      - ../../configs/user-service.env
      - ../../configs/network-info.env

    networks:
      - common-network
