services:
  video-manager:
    container_name: video-manager
    restart: unless-stopped
    build:
      context: '../..'
      dockerfile: '/apps/video_manager/Dockerfile'
    depends_on:
      - mongodb
    env_file:
      - deployment/configs/project_base_info/user-service.env
      - deployment/configs/project_personal_info/user-service.env

    networks:
      - common-network
